name: Raspagem Semanal

on:
  schedule:
    - cron: '0 6 * * 1' # Executa toda segunda-feira às 6h UTC
  workflow_dispatch:

jobs:
  raspagem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Executar raspagem
        env:
          URL_ALVO: "https://servicos.semobjp.pb.gov.br/linhas-de-onibus/" # Substitua pela URL REAL
        run: python raspagem.py

      - name: Commitar alterações (se houver)
        uses: stefanzweifel/git-commit-message@v2
        with:
          commit_message: "Atualização dos dados de ônibus"
        continue-on-error: true

      - name: Enviar alterações para o repositório
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true